from __future__ import annotations

MOCK_TICKERS = {
    "SHOP.TO": {
        "ticker": "SHOP.TO", "company_name": "Shopify Inc.", "market": "Canada",
        "sector": "Technology", "industry": "Software", "current_price": 95.00,
        "currency": "CAD", "daily_change_pct": 1.2, "two_week_trend_pct": 4.8,
        "three_month_trend_pct": 13.5, "one_year_trend_pct": 28.0,
        "market_cap": 120_000_000_000, "trailing_pe": 72.0, "forward_pe": 48.0,
        "price_to_sales": 11.0, "revenue_growth": 0.24, "earnings_growth": 0.18,
        "profit_margins": 0.12, "debt_to_equity": 12.0, "free_cashflow": 950_000_000,
        "total_cash": 5_000_000_000, "history": [], "data_source": "Mock fallback",
        "data_quality": "Mock data only", "error": None,
    },
    "RY.TO": {
        "ticker": "RY.TO", "company_name": "Royal Bank of Canada", "market": "Canada",
        "sector": "Financial Services", "industry": "Banks", "current_price": 155.00,
        "currency": "CAD", "daily_change_pct": 0.2, "two_week_trend_pct": 1.4,
        "three_month_trend_pct": 4.5, "one_year_trend_pct": 12.0,
        "market_cap": 220_000_000_000, "trailing_pe": 14.0, "forward_pe": 12.0,
        "price_to_sales": 4.0, "revenue_growth": 0.07, "earnings_growth": 0.08,
        "profit_margins": 0.28, "debt_to_equity": 80.0, "free_cashflow": None,
        "total_cash": None, "history": [], "data_source": "Mock fallback",
        "data_quality": "Mock data only", "error": None,
    },
    "MSFT": {
        "ticker": "MSFT", "company_name": "Microsoft Corporation", "market": "U.S.",
        "sector": "Technology", "industry": "Software", "current_price": 430.00,
        "currency": "USD", "daily_change_pct": 0.6, "two_week_trend_pct": 2.1,
        "three_month_trend_pct": 9.0, "one_year_trend_pct": 22.0,
        "market_cap": 3_200_000_000_000, "trailing_pe": 36.0, "forward_pe": 31.0,
        "price_to_sales": 12.0, "revenue_growth": 0.16, "earnings_growth": 0.18,
        "profit_margins": 0.36, "debt_to_equity": 24.0, "free_cashflow": 70_000_000_000,
        "total_cash": 80_000_000_000, "history": [], "data_source": "Mock fallback",
        "data_quality": "Mock data only", "error": None,
    },
    "NVDA": {
        "ticker": "NVDA", "company_name": "NVIDIA Corporation", "market": "U.S.",
        "sector": "Technology", "industry": "Semiconductors", "current_price": 135.00,
        "currency": "USD", "daily_change_pct": 1.9, "two_week_trend_pct": 7.5,
        "three_month_trend_pct": 24.0, "one_year_trend_pct": 85.0,
        "market_cap": 3_300_000_000_000, "trailing_pe": 58.0, "forward_pe": 38.0,
        "price_to_sales": 25.0, "revenue_growth": 0.75, "earnings_growth": 0.95,
        "profit_margins": 0.49, "debt_to_equity": 18.0, "free_cashflow": 40_000_000_000,
        "total_cash": 30_000_000_000, "history": [], "data_source": "Mock fallback",
        "data_quality": "Mock data only", "error": None,
    },
    "AAPL": {
        "ticker": "AAPL", "company_name": "Apple Inc.", "market": "U.S.",
        "sector": "Technology", "industry": "Consumer Electronics", "current_price": 205.00,
        "currency": "USD", "daily_change_pct": -0.2, "two_week_trend_pct": 1.0,
        "three_month_trend_pct": 3.5, "one_year_trend_pct": 8.0,
        "market_cap": 3_000_000_000_000, "trailing_pe": 30.0, "forward_pe": 27.0,
        "price_to_sales": 8.0, "revenue_growth": 0.04, "earnings_growth": 0.06,
        "profit_margins": 0.26, "debt_to_equity": 145.0, "free_cashflow": 95_000_000_000,
        "total_cash": 62_000_000_000, "history": [], "data_source": "Mock fallback",
        "data_quality": "Mock data only", "error": None,
    },
    "VFV.TO": {
        "ticker": "VFV.TO", "company_name": "Vanguard S&P 500 Index ETF",
        "market": "Canada", "sector": "ETF", "industry": "Broad Market ETF",
        "current_price": 145.00, "currency": "CAD", "daily_change_pct": 0.3,
        "two_week_trend_pct": 1.1, "three_month_trend_pct": 5.0, "one_year_trend_pct": 17.0,
        "market_cap": None, "trailing_pe": None, "forward_pe": None, "price_to_sales": None,
        "revenue_growth": None, "earnings_growth": None, "profit_margins": None,
        "debt_to_equity": None, "free_cashflow": None, "total_cash": None,
        "history": [], "data_source": "Mock fallback", "data_quality": "Mock data only",
        "error": None,
    },
}

DEFAULT_MOCK = {
    "ticker": "MOCK", "company_name": "Mock Company", "market": "Unknown",
    "sector": "Unknown", "industry": "Unknown", "current_price": 50.00,
    "currency": "USD", "daily_change_pct": 0.0, "two_week_trend_pct": 0.0,
    "three_month_trend_pct": 0.0, "one_year_trend_pct": 0.0,
    "market_cap": 1_000_000_000, "trailing_pe": 25.0, "forward_pe": 22.0,
    "price_to_sales": 4.0, "revenue_growth": 0.10, "earnings_growth": 0.08,
    "profit_margins": 0.10, "debt_to_equity": 35.0, "free_cashflow": 50_000_000,
    "total_cash": 100_000_000, "history": [], "data_source": "Mock fallback",
    "data_quality": "Mock data only", "error": None,
}
